// Code generated by protoc-gen-go-http. DO NOT EDIT.

package mesh

import (
	context "context"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http.
const _ = http1.SupportPackageIsVersion1

type MeshHTTPServer interface {
	CheckInfo(context.Context, *Request) (*Response, error)

	CreateGateway(context.Context, *Gateway) (*Response, error)

	GetGatewayList(context.Context, *GetGatewayOption) (*GatewayList, error)
}

func RegisterMeshHTTPServer(s http1.ServiceRegistrar, srv MeshHTTPServer) {
	s.RegisterService(&_HTTP_Mesh_serviceDesc, srv)
}

func _HTTP_Mesh_CheckInfo_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in Request

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	out, err := srv.(MeshServer).CheckInfo(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Mesh_GetGatewayList_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in GetGatewayOption

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	out, err := srv.(MeshServer).GetGatewayList(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Mesh_CreateGateway_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in Gateway

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	out, err := srv.(MeshServer).CreateGateway(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_Mesh_serviceDesc = http1.ServiceDesc{
	ServiceName: "cratos.service.v1.Mesh",
	Methods: []http1.MethodDesc{

		{
			Path:    "/cratos.service.v1.Mesh/CheckInfo",
			Method:  "POST",
			Handler: _HTTP_Mesh_CheckInfo_0,
		},

		{
			Path:    "/cratos.service.v1.Mesh/GetGatewayList",
			Method:  "POST",
			Handler: _HTTP_Mesh_GetGatewayList_0,
		},

		{
			Path:    "/cratos.service.v1.Mesh/CreateGateway",
			Method:  "POST",
			Handler: _HTTP_Mesh_CreateGateway_0,
		},
	},
	Metadata: "mesh.proto",
}
