// @ts-ignore
/* eslint-disable */
// Code generated by protoc-gen-ts-umi. DO NOT EDIT.

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.

declare namespace CratosApiV1Namespace {
	/** DeleteKind */
	type DeleteKind = {
		name?:string
		namespace?:string
	}
	/** Request */
	type Request = {
	}
	/** Response */
	type Response = {
	}
	/** ListOption */
	type ListOption = {
		limit?:number
		Offset?:number
		sort?:string
		name?:string
		namespace?:string
	}
	/** NamespaceList */
	type NamespaceList = {
		list?:Array<K8sIoApiCoreV1.Namespace>
		total?:number
	}
	/** GetKind */
	type GetKind = {
		name?:string
		namespace?:string
		version?:string
	}
}

declare namespace K8sIoApiCoreV1 {
	/** NamespaceSpec */
	type NamespaceSpec = {
		finalizers?:Array<string>
	}
	/** NamespaceStatus */
	type NamespaceStatus = {
		phase?:string
		conditions?:Array<K8sIoApiCoreV1.NamespaceCondition>
	}
	/** NamespaceCondition */
	type NamespaceCondition = {
		type?:string
		status?:string
		lastTransitionTime?:K8sIoApimachineryPkgApisMetaV1.Time
		reason?:string
		message?:string
	}
	/** Namespace */
	type Namespace = {
		metadata?:K8sIoApimachineryPkgApisMetaV1.ObjectMeta
		spec?:K8sIoApiCoreV1.NamespaceSpec
		status?:K8sIoApiCoreV1.NamespaceStatus
	}
}

declare namespace K8sIoApimachineryPkgApisMetaV1 {
	/** FieldsV1 */
	type FieldsV1 = {
		Raw?:string
	}
	/** ObjectMeta */
	type ObjectMeta = {
		name?:string
		generateName?:string
		namespace?:string
		selfLink?:string
		uid?:string
		resourceVersion?:string
		generation?:number
		creationTimestamp?:K8sIoApimachineryPkgApisMetaV1.Time
		deletionTimestamp?:K8sIoApimachineryPkgApisMetaV1.Time
		deletionGracePeriodSeconds?:number
		labels?:Map<string,string>
		annotations?:Map<string,string>
		ownerReferences?:Array<K8sIoApimachineryPkgApisMetaV1.OwnerReference>
		finalizers?:Array<string>
		clusterName?:string
		managedFields?:Array<K8sIoApimachineryPkgApisMetaV1.ManagedFieldsEntry>
	}
	/** Time */
	type Time = {
		seconds?:number
		nanos?:number
	}
	/** LabelsEntry */
	type LabelsEntry = {
		key?:string
		value?:string
	}
	/** AnnotationsEntry */
	type AnnotationsEntry = {
		key?:string
		value?:string
	}
	/** OwnerReference */
	type OwnerReference = {
		apiVersion?:string
		kind?:string
		name?:string
		uid?:string
		controller?:boolean
		blockOwnerDeletion?:boolean
	}
	/** ManagedFieldsEntry */
	type ManagedFieldsEntry = {
		manager?:string
		operation?:string
		apiVersion?:string
		time?:K8sIoApimachineryPkgApisMetaV1.Time
		fieldsType?:string
		fieldsV1?:K8sIoApimachineryPkgApisMetaV1.FieldsV1
	}
}

