server:
  http:
    addr: 0.0.0.0:9002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  istio:
    config: ./config
  kube:
    config: ./config
  database:
    driver: sqlite
    source: ./data.db